CREATE TABLE KEY_CARD(
    ID INTEGER IDENTITY PRIMARY KEY,
    K_ID varchar(100) NULL,
    CARD_DATA_ID INTEGER NULL
)
;
CREATE TABLE CARD_DATA(
    ID INTEGER IDENTITY PRIMARY KEY,
    CARD_NBR varchar(100) NULL,
    CARD_NME varchar(30) NULL,
    CARD_EXPIRATION_MONTH_YEAR datetime NULL,
    CARD_SECURITY varchar(5) NULL,
    CARD_VALUE decimal NULL,
    CARD_FLAG varchar(50) NULL,
)
;
CREATE TABLE CONTRACT_DATA(
    ID INTEGER IDENTITY PRIMARY KEY,
    CONTRACT_NUMBER varchar(20) NULL,
    CONTRACT_INSERT_DATE datetime NULL
    CONTRACT_UPDATE_DATE datetime NULL,
    CARD_DATA_ID INTEGER NULL,
    UPDATE_USER_ID INTEGER NULL,
    UPDATE_USER_DOC varchar(20) NULL,
    UPDATE_USER_DOC_TYPE varchar(10)NULL,
)
;