package br.com.cardif.wsdirectsales;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5 2016-03-17T10:25:29.387-03:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://wsdirectsales.cardif.com.br/", name = "CustomerSalesService")
@XmlSeeAlso({ ObjectFactory.class })
public interface CustomerSalesService {

    @WebMethod(action = "http://wsdirectsales.cardif.com.br/retrieveCustomer")
    @RequestWrapper(localName = "retrieveCustomer", targetNamespace = "http://wsdirectsales.cardif.com.br/", className = "br.com.cardif.wsdirectsales.RetrieveCustomerIN")
    @ResponseWrapper(localName = "retrieveCustomerResponse", targetNamespace = "http://wsdirectsales.cardif.com.br/", className = "br.com.cardif.wsdirectsales.RetrieveCustomerOUT")
    @WebResult(name = "retrieveCustomerResponse", targetNamespace = "")
    public br.com.cardif.wsdirectsales.RetrieveCustomerResponse retrieveCustomer(
            @WebParam(name = "retrieveCustomerRequest", targetNamespace = "") br.com.cardif.wsdirectsales.RetrieveCustomerRequest retrieveCustomerRequest);

    @WebMethod(action = "http://wsdirectsales.cardif.com.br/retrieveCommissions")
    @RequestWrapper(localName = "retrieveCommissions", targetNamespace = "http://wsdirectsales.cardif.com.br/", className = "br.com.cardif.wsdirectsales.RetrieveCommissionsIN")
    @ResponseWrapper(localName = "retrieveCommissionsResponse", targetNamespace = "http://wsdirectsales.cardif.com.br/", className = "br.com.cardif.wsdirectsales.RetrieveCommissionsOUT")
    @WebResult(name = "retrieveCommissionsResponse", targetNamespace = "")
    public br.com.cardif.wsdirectsales.RetrieveCommissionsResponse retrieveCommissions(
            @WebParam(name = "retrieveCommissionsRequest", targetNamespace = "") br.com.cardif.wsdirectsales.RetrieveCommissionsRequest retrieveCommissionsRequest);

    @WebMethod(action = "http://wsdirectsales.cardif.com.br/doSale")
    @RequestWrapper(localName = "doSale", targetNamespace = "http://wsdirectsales.cardif.com.br/", className = "br.com.cardif.wsdirectsales.DoSaleIN")
    @ResponseWrapper(localName = "doSaleResponse", targetNamespace = "http://wsdirectsales.cardif.com.br/", className = "br.com.cardif.wsdirectsales.DoSaleOUT")
    @WebResult(name = "doSaleResponse", targetNamespace = "")
    public br.com.cardif.wsdirectsales.DoSaleResponse doSale(
            @WebParam(name = "doSaleRequest", targetNamespace = "") br.com.cardif.wsdirectsales.DoSaleRequest doSaleRequest);

    @WebMethod(action = "http://wsdirectsales.cardif.com.br/retrieveSales")
    @RequestWrapper(localName = "retrieveSales", targetNamespace = "http://wsdirectsales.cardif.com.br/", className = "br.com.cardif.wsdirectsales.RetrieveSalesIN")
    @ResponseWrapper(localName = "retrieveSalesResponse", targetNamespace = "http://wsdirectsales.cardif.com.br/", className = "br.com.cardif.wsdirectsales.RetrieveSalesOUT")
    @WebResult(name = "retrieveSalesResponse", targetNamespace = "")
    public br.com.cardif.wsdirectsales.RetrieveSalesResponse retrieveSales(
            @WebParam(name = "retrieveSalesRequest", targetNamespace = "") br.com.cardif.wsdirectsales.RetrieveSalesRequest retrieveSalesRequest);
}
