package br.com.cardif.wsdirectsales;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5 2016-03-17T10:25:29.480-03:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "CustomerSalesService", wsdlLocation = "http://172.17.121.20:8082/wsdirectsales/CustomerSalesService?wsdl", targetNamespace = "http://wsdirectsales.cardif.com.br/")
public class CustomerSalesService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsdirectsales.cardif.com.br/", "CustomerSalesService");
    public final static QName CustomerSalesServicePort = new QName("http://wsdirectsales.cardif.com.br/",
            "CustomerSalesServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.17.121.20:8082/wsdirectsales/CustomerSalesService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerSalesService_Service.class.getName()).log(
                    java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
                    "http://172.17.121.20:8082/wsdirectsales/CustomerSalesService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerSalesService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerSalesService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerSalesService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerSalesService_Service(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerSalesService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerSalesService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns CustomerSalesService
     */
    @WebEndpoint(name = "CustomerSalesServicePort")
    public CustomerSalesService getCustomerSalesServicePort() {
        return super.getPort(CustomerSalesServicePort, CustomerSalesService.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns CustomerSalesService
     */
    @WebEndpoint(name = "CustomerSalesServicePort")
    public CustomerSalesService getCustomerSalesServicePort(WebServiceFeature... features) {
        return super.getPort(CustomerSalesServicePort, CustomerSalesService.class, features);
    }

}
