//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSDirectSales.wsdirectsales {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerSalesServiceSoapBinding", Namespace="http://wsdirectsales.cardif.com.br/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(identification))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personDTO))]
    public partial class CustomerSalesService : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback retrieveCustomerSalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrievePerformanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrieveCommissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback doSaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback updatePaymentMethodOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerSalesService() {
            this.Url = global::WSDirectSales.Properties.Settings.Default.WSDirectSales_wsdirectsales_CustomerSalesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event retrieveCustomerSalesCompletedEventHandler retrieveCustomerSalesCompleted;
        
        /// <remarks/>
        public event retrievePerformanceCompletedEventHandler retrievePerformanceCompleted;
        
        /// <remarks/>
        public event retrieveCommissionsCompletedEventHandler retrieveCommissionsCompleted;
        
        /// <remarks/>
        public event doSaleCompletedEventHandler doSaleCompleted;
        
        /// <remarks/>
        public event updatePaymentMethodCompletedEventHandler updatePaymentMethodCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsdirectsales.cardif.com.br/retrieveCustomerSales", RequestNamespace="http://wsdirectsales.cardif.com.br/", ResponseNamespace="http://wsdirectsales.cardif.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("retrieveCustomerSalesResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retrieveCustomerSalesResponse retrieveCustomerSales([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrieveCustomerSalesRequest retrieveCustomerSalesRequest) {
            object[] results = this.Invoke("retrieveCustomerSales", new object[] {
                        retrieveCustomerSalesRequest});
            return ((retrieveCustomerSalesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void retrieveCustomerSalesAsync(retrieveCustomerSalesRequest retrieveCustomerSalesRequest) {
            this.retrieveCustomerSalesAsync(retrieveCustomerSalesRequest, null);
        }
        
        /// <remarks/>
        public void retrieveCustomerSalesAsync(retrieveCustomerSalesRequest retrieveCustomerSalesRequest, object userState) {
            if ((this.retrieveCustomerSalesOperationCompleted == null)) {
                this.retrieveCustomerSalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveCustomerSalesOperationCompleted);
            }
            this.InvokeAsync("retrieveCustomerSales", new object[] {
                        retrieveCustomerSalesRequest}, this.retrieveCustomerSalesOperationCompleted, userState);
        }
        
        private void OnretrieveCustomerSalesOperationCompleted(object arg) {
            if ((this.retrieveCustomerSalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveCustomerSalesCompleted(this, new retrieveCustomerSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsdirectsales.cardif.com.br/retrievePerformance", RequestNamespace="http://wsdirectsales.cardif.com.br/", ResponseNamespace="http://wsdirectsales.cardif.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("retrievePerformanceResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retrievePerformanceResponse retrievePerformance([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrievePerformanceRequest retrievePerformanceRequest) {
            object[] results = this.Invoke("retrievePerformance", new object[] {
                        retrievePerformanceRequest});
            return ((retrievePerformanceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void retrievePerformanceAsync(retrievePerformanceRequest retrievePerformanceRequest) {
            this.retrievePerformanceAsync(retrievePerformanceRequest, null);
        }
        
        /// <remarks/>
        public void retrievePerformanceAsync(retrievePerformanceRequest retrievePerformanceRequest, object userState) {
            if ((this.retrievePerformanceOperationCompleted == null)) {
                this.retrievePerformanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrievePerformanceOperationCompleted);
            }
            this.InvokeAsync("retrievePerformance", new object[] {
                        retrievePerformanceRequest}, this.retrievePerformanceOperationCompleted, userState);
        }
        
        private void OnretrievePerformanceOperationCompleted(object arg) {
            if ((this.retrievePerformanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrievePerformanceCompleted(this, new retrievePerformanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsdirectsales.cardif.com.br/retrieveCommissions", RequestNamespace="http://wsdirectsales.cardif.com.br/", ResponseNamespace="http://wsdirectsales.cardif.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("retrieveCommissionsResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public retrieveCommissionsResponse retrieveCommissions([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] retrieveCommissionsRequest retrieveCommissionsRequest) {
            object[] results = this.Invoke("retrieveCommissions", new object[] {
                        retrieveCommissionsRequest});
            return ((retrieveCommissionsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void retrieveCommissionsAsync(retrieveCommissionsRequest retrieveCommissionsRequest) {
            this.retrieveCommissionsAsync(retrieveCommissionsRequest, null);
        }
        
        /// <remarks/>
        public void retrieveCommissionsAsync(retrieveCommissionsRequest retrieveCommissionsRequest, object userState) {
            if ((this.retrieveCommissionsOperationCompleted == null)) {
                this.retrieveCommissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveCommissionsOperationCompleted);
            }
            this.InvokeAsync("retrieveCommissions", new object[] {
                        retrieveCommissionsRequest}, this.retrieveCommissionsOperationCompleted, userState);
        }
        
        private void OnretrieveCommissionsOperationCompleted(object arg) {
            if ((this.retrieveCommissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveCommissionsCompleted(this, new retrieveCommissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsdirectsales.cardif.com.br/doSale", RequestNamespace="http://wsdirectsales.cardif.com.br/", ResponseNamespace="http://wsdirectsales.cardif.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("doSaleResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public doSaleResponse doSale([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] doSaleRequest doSaleRequest) {
            object[] results = this.Invoke("doSale", new object[] {
                        doSaleRequest});
            return ((doSaleResponse)(results[0]));
        }
        
        /// <remarks/>
        public void doSaleAsync(doSaleRequest doSaleRequest) {
            this.doSaleAsync(doSaleRequest, null);
        }
        
        /// <remarks/>
        public void doSaleAsync(doSaleRequest doSaleRequest, object userState) {
            if ((this.doSaleOperationCompleted == null)) {
                this.doSaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoSaleOperationCompleted);
            }
            this.InvokeAsync("doSale", new object[] {
                        doSaleRequest}, this.doSaleOperationCompleted, userState);
        }
        
        private void OndoSaleOperationCompleted(object arg) {
            if ((this.doSaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doSaleCompleted(this, new doSaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsdirectsales.cardif.com.br/updatePaymentMethod", RequestNamespace="http://wsdirectsales.cardif.com.br/", ResponseNamespace="http://wsdirectsales.cardif.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("updatePaymentMethodResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public updatePaymentMethodResponse updatePaymentMethod([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] updatePaymentMethodRequest updatePaymentMethodRequest) {
            object[] results = this.Invoke("updatePaymentMethod", new object[] {
                        updatePaymentMethodRequest});
            return ((updatePaymentMethodResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updatePaymentMethodAsync(updatePaymentMethodRequest updatePaymentMethodRequest) {
            this.updatePaymentMethodAsync(updatePaymentMethodRequest, null);
        }
        
        /// <remarks/>
        public void updatePaymentMethodAsync(updatePaymentMethodRequest updatePaymentMethodRequest, object userState) {
            if ((this.updatePaymentMethodOperationCompleted == null)) {
                this.updatePaymentMethodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdatePaymentMethodOperationCompleted);
            }
            this.InvokeAsync("updatePaymentMethod", new object[] {
                        updatePaymentMethodRequest}, this.updatePaymentMethodOperationCompleted, userState);
        }
        
        private void OnupdatePaymentMethodOperationCompleted(object arg) {
            if ((this.updatePaymentMethodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updatePaymentMethodCompleted(this, new updatePaymentMethodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class retrieveCustomerSalesRequest {
        
        private customer customerField;
        
        private @operator operatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customer customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public @operator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class customer : systemPerson {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@operator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(salesman))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class systemPerson : personDTO {
        
        private string descriptionField;
        
        private int drtIDField;
        
        private bool drtIDFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private loginDTO loginField;
        
        private int mlIDField;
        
        private bool mlIDFieldSpecified;
        
        private partner partnerField;
        
        private string roleField;
        
        private int sUPField;
        
        private bool sUPFieldSpecified;
        
        private int typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int drtID {
            get {
                return this.drtIDField;
            }
            set {
                this.drtIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool drtIDSpecified {
            get {
                return this.drtIDFieldSpecified;
            }
            set {
                this.drtIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public loginDTO login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mlID {
            get {
                return this.mlIDField;
            }
            set {
                this.mlIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mlIDSpecified {
            get {
                return this.mlIDFieldSpecified;
            }
            set {
                this.mlIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public partner partner {
            get {
                return this.partnerField;
            }
            set {
                this.partnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SUP {
            get {
                return this.sUPField;
            }
            set {
                this.sUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUPSpecified {
            get {
                return this.sUPFieldSpecified;
            }
            set {
                this.sUPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class loginDTO : identification {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(coverage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(capitalSeries))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(certificateDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(insuranceCertificate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cardPaymentDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(paymentMethod))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(partner))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(workshop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(regional))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(loginDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class identification {
        
        private string descriptionField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class updatePaymentMethodResponse {
        
        private bool updatedField;
        
        private bool updatedFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedSpecified {
            get {
                return this.updatedFieldSpecified;
            }
            set {
                this.updatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class updatePaymentMethodRequest {
        
        private insuranceCertificate certificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public insuranceCertificate certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class insuranceCertificate : certificateDTO {
        
        private coverage[] coveragesField;
        
        private customer customerField;
        
        private paymentMethod paymentMethodField;
        
        private insuranceDTO productField;
        
        private decimal saleCommissionValueField;
        
        private bool saleCommissionValueFieldSpecified;
        
        private salesman salesmanField;
        
        private tax[] taxesField;
        
        private workshop workshopField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public coverage[] coverages {
            get {
                return this.coveragesField;
            }
            set {
                this.coveragesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customer customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public paymentMethod paymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public insuranceDTO product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal saleCommissionValue {
            get {
                return this.saleCommissionValueField;
            }
            set {
                this.saleCommissionValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saleCommissionValueSpecified {
            get {
                return this.saleCommissionValueFieldSpecified;
            }
            set {
                this.saleCommissionValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public salesman salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tax[] taxes {
            get {
                return this.taxesField;
            }
            set {
                this.taxesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public workshop workshop {
            get {
                return this.workshopField;
            }
            set {
                this.workshopField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class coverage : identification {
        
        private decimal coveragePremiumField;
        
        private bool coveragePremiumFieldSpecified;
        
        private decimal coverageValueLimitField;
        
        private bool coverageValueLimitFieldSpecified;
        
        private int installmentLimitField;
        
        private bool installmentLimitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal coveragePremium {
            get {
                return this.coveragePremiumField;
            }
            set {
                this.coveragePremiumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coveragePremiumSpecified {
            get {
                return this.coveragePremiumFieldSpecified;
            }
            set {
                this.coveragePremiumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal coverageValueLimit {
            get {
                return this.coverageValueLimitField;
            }
            set {
                this.coverageValueLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coverageValueLimitSpecified {
            get {
                return this.coverageValueLimitFieldSpecified;
            }
            set {
                this.coverageValueLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int installmentLimit {
            get {
                return this.installmentLimitField;
            }
            set {
                this.installmentLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool installmentLimitSpecified {
            get {
                return this.installmentLimitFieldSpecified;
            }
            set {
                this.installmentLimitFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class paymentMethod : identification {
        
        private cardPaymentDTO cardPaymentField;
        
        private int paymentTypeField;
        
        private bool paymentTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cardPaymentDTO cardPayment {
            get {
                return this.cardPaymentField;
            }
            set {
                this.cardPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentTypeSpecified {
            get {
                return this.paymentTypeFieldSpecified;
            }
            set {
                this.paymentTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class cardPaymentDTO : identification {
        
        private string cardDisplayNameField;
        
        private string cardFlagField;
        
        private string cardNumberField;
        
        private string cardSecurityCodeField;
        
        private System.DateTime cardValidityField;
        
        private bool cardValidityFieldSpecified;
        
        private decimal cardValueField;
        
        private bool cardValueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardDisplayName {
            get {
                return this.cardDisplayNameField;
            }
            set {
                this.cardDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardFlag {
            get {
                return this.cardFlagField;
            }
            set {
                this.cardFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardSecurityCode {
            get {
                return this.cardSecurityCodeField;
            }
            set {
                this.cardSecurityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime cardValidity {
            get {
                return this.cardValidityField;
            }
            set {
                this.cardValidityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cardValiditySpecified {
            get {
                return this.cardValidityFieldSpecified;
            }
            set {
                this.cardValidityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal cardValue {
            get {
                return this.cardValueField;
            }
            set {
                this.cardValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cardValueSpecified {
            get {
                return this.cardValueFieldSpecified;
            }
            set {
                this.cardValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class insuranceDTO : productDTO {
        
        private decimal premiumValueField;
        
        private bool premiumValueFieldSpecified;
        
        private insuranceStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal premiumValue {
            get {
                return this.premiumValueField;
            }
            set {
                this.premiumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool premiumValueSpecified {
            get {
                return this.premiumValueFieldSpecified;
            }
            set {
                this.premiumValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public insuranceStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public enum insuranceStatus {
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        REFUSED,
        
        /// <remarks/>
        PROPOSAL,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(insuranceDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class productDTO {
        
        private string descriptonField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripton {
            get {
                return this.descriptonField;
            }
            set {
                this.descriptonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class salesman : @operator {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(salesman))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class @operator : systemPerson {
        
        private string operatorNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class tax {
        
        private taxType taxTypeField;
        
        private bool taxTypeFieldSpecified;
        
        private string taxValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taxType taxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxTypeSpecified {
            get {
                return this.taxTypeFieldSpecified;
            }
            set {
                this.taxTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxValue {
            get {
                return this.taxValueField;
            }
            set {
                this.taxValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public enum taxType {
        
        /// <remarks/>
        IOF,
        
        /// <remarks/>
        PROLABORE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class workshop : identification {
        
        private int regionalIDField;
        
        private bool regionalIDFieldSpecified;
        
        private salesman[] sallersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int regionalID {
            get {
                return this.regionalIDField;
            }
            set {
                this.regionalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool regionalIDSpecified {
            get {
                return this.regionalIDFieldSpecified;
            }
            set {
                this.regionalIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sallers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public salesman[] sallers {
            get {
                return this.sallersField;
            }
            set {
                this.sallersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(insuranceCertificate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class certificateDTO : identification {
        
        private capitalSeries capitalSeriesField;
        
        private System.DateTime certificateCreationDateField;
        
        private bool certificateCreationDateFieldSpecified;
        
        private System.DateTime certificateValidityEndDateField;
        
        private bool certificateValidityEndDateFieldSpecified;
        
        private System.DateTime certificateValidityInitDateField;
        
        private bool certificateValidityInitDateFieldSpecified;
        
        private string contractNumberField;
        
        private string policeNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public capitalSeries capitalSeries {
            get {
                return this.capitalSeriesField;
            }
            set {
                this.capitalSeriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime certificateCreationDate {
            get {
                return this.certificateCreationDateField;
            }
            set {
                this.certificateCreationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certificateCreationDateSpecified {
            get {
                return this.certificateCreationDateFieldSpecified;
            }
            set {
                this.certificateCreationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime certificateValidityEndDate {
            get {
                return this.certificateValidityEndDateField;
            }
            set {
                this.certificateValidityEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certificateValidityEndDateSpecified {
            get {
                return this.certificateValidityEndDateFieldSpecified;
            }
            set {
                this.certificateValidityEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime certificateValidityInitDate {
            get {
                return this.certificateValidityInitDateField;
            }
            set {
                this.certificateValidityInitDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certificateValidityInitDateSpecified {
            get {
                return this.certificateValidityInitDateFieldSpecified;
            }
            set {
                this.certificateValidityInitDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string policeNumber {
            get {
                return this.policeNumberField;
            }
            set {
                this.policeNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class capitalSeries : identification {
        
        private string capitalNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string capitalNumber {
            get {
                return this.capitalNumberField;
            }
            set {
                this.capitalNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class doSaleResponse {
        
        private insuranceCertificate certificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public insuranceCertificate certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class sale {
        
        private customer customerField;
        
        private paymentMethod paymentMethodField;
        
        private productDTO productField;
        
        private salesman salesmanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customer customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public paymentMethod paymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public productDTO product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public salesman salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class doSaleRequest {
        
        private sale saleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sale sale {
            get {
                return this.saleField;
            }
            set {
                this.saleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class retrieveCommissionsResponse {
        
        private insuranceCertificate[] certificatesField;
        
        private System.Nullable<int> pageCountField;
        
        private bool pageCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("certificates", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public insuranceCertificate[] certificates {
            get {
                return this.certificatesField;
            }
            set {
                this.certificatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageCountSpecified {
            get {
                return this.pageCountFieldSpecified;
            }
            set {
                this.pageCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class retrieveCommissionsRequest {
        
        private salesman salesmanField;
        
        private @operator operatorField;
        
        private int pageNumberField;
        
        private bool pageNumberFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public salesman salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public @operator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumberSpecified {
            get {
                return this.pageNumberFieldSpecified;
            }
            set {
                this.pageNumberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class salesmanScore {
        
        private long activeCertificatesQtyField;
        
        private bool activeCertificatesQtyFieldSpecified;
        
        private double activeCertificatesValueField;
        
        private bool activeCertificatesValueFieldSpecified;
        
        private productDTO productField;
        
        private regional regionalField;
        
        private salesman salesmanField;
        
        private tax[] taxesField;
        
        private coverage[] coveragesField;
        
        private double totalCommissionValueField;
        
        private bool totalCommissionValueFieldSpecified;
        
        private workshop workshopField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long activeCertificatesQty {
            get {
                return this.activeCertificatesQtyField;
            }
            set {
                this.activeCertificatesQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeCertificatesQtySpecified {
            get {
                return this.activeCertificatesQtyFieldSpecified;
            }
            set {
                this.activeCertificatesQtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double activeCertificatesValue {
            get {
                return this.activeCertificatesValueField;
            }
            set {
                this.activeCertificatesValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeCertificatesValueSpecified {
            get {
                return this.activeCertificatesValueFieldSpecified;
            }
            set {
                this.activeCertificatesValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public productDTO product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public regional regional {
            get {
                return this.regionalField;
            }
            set {
                this.regionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public salesman salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tax[] taxes {
            get {
                return this.taxesField;
            }
            set {
                this.taxesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public coverage[] coverages {
            get {
                return this.coveragesField;
            }
            set {
                this.coveragesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double totalCommissionValue {
            get {
                return this.totalCommissionValueField;
            }
            set {
                this.totalCommissionValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCommissionValueSpecified {
            get {
                return this.totalCommissionValueFieldSpecified;
            }
            set {
                this.totalCommissionValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public workshop workshop {
            get {
                return this.workshopField;
            }
            set {
                this.workshopField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class regional : identification {
        
        private workshop[] workshopsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("workshops", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public workshop[] workshops {
            get {
                return this.workshopsField;
            }
            set {
                this.workshopsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class retrievePerformanceResponse {
        
        private salesmanScore[] scoreField;
        
        private decimal commissionValueTotalField;
        
        private bool commissionValueTotalFieldSpecified;
        
        private long activeCertificatesQtyTotalField;
        
        private bool activeCertificatesQtyTotalFieldSpecified;
        
        private decimal activeCertificatesValueTotalField;
        
        private bool activeCertificatesValueTotalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("score", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public salesmanScore[] score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal commissionValueTotal {
            get {
                return this.commissionValueTotalField;
            }
            set {
                this.commissionValueTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commissionValueTotalSpecified {
            get {
                return this.commissionValueTotalFieldSpecified;
            }
            set {
                this.commissionValueTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long activeCertificatesQtyTotal {
            get {
                return this.activeCertificatesQtyTotalField;
            }
            set {
                this.activeCertificatesQtyTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeCertificatesQtyTotalSpecified {
            get {
                return this.activeCertificatesQtyTotalFieldSpecified;
            }
            set {
                this.activeCertificatesQtyTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal activeCertificatesValueTotal {
            get {
                return this.activeCertificatesValueTotalField;
            }
            set {
                this.activeCertificatesValueTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeCertificatesValueTotalSpecified {
            get {
                return this.activeCertificatesValueTotalFieldSpecified;
            }
            set {
                this.activeCertificatesValueTotalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class retrievePerformanceRequest {
        
        private productDTO productField;
        
        private regional regionalField;
        
        private workshop workshopField;
        
        private salesman salesmanField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public productDTO product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public regional regional {
            get {
                return this.regionalField;
            }
            set {
                this.regionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public workshop workshop {
            get {
                return this.workshopField;
            }
            set {
                this.workshopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public salesman salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class retrieveCustomerSalesResponse {
        
        private insuranceCertificate[] certificatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("certificate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public insuranceCertificate[] certificates {
            get {
                return this.certificatesField;
            }
            set {
                this.certificatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class identityDTO {
        
        private document documentTypeField;
        
        private bool documentTypeFieldSpecified;
        
        private string documentValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public document documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentTypeSpecified {
            get {
                return this.documentTypeFieldSpecified;
            }
            set {
                this.documentTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentValue {
            get {
                return this.documentValueField;
            }
            set {
                this.documentValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public enum document {
        
        /// <remarks/>
        CPF,
        
        /// <remarks/>
        CNPJ,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class phoneDTO {
        
        private string phoneNumberField;
        
        private phoneType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public phoneType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public enum phoneType {
        
        /// <remarks/>
        RESIDENTIAL,
        
        /// <remarks/>
        MOBILE,
        
        /// <remarks/>
        BUSINESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class addressDTO {
        
        private string addressDetailField;
        
        private string addressNumberField;
        
        private string addressPostalCodeField;
        
        private string addressReferenceField;
        
        private string cityField;
        
        private string neighborhoodField;
        
        private string stateField;
        
        private addressType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addressDetail {
            get {
                return this.addressDetailField;
            }
            set {
                this.addressDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addressNumber {
            get {
                return this.addressNumberField;
            }
            set {
                this.addressNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addressPostalCode {
            get {
                return this.addressPostalCodeField;
            }
            set {
                this.addressPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addressReference {
            get {
                return this.addressReferenceField;
            }
            set {
                this.addressReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string neighborhood {
            get {
                return this.neighborhoodField;
            }
            set {
                this.neighborhoodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public addressType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public enum addressType {
        
        /// <remarks/>
        RESIDENTIAL,
        
        /// <remarks/>
        BUSINESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class contactDTO {
        
        private addressDTO addressField;
        
        private phoneDTO phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public addressDTO address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public phoneDTO phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(systemPerson))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@operator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(salesman))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class personDTO {
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private contactDTO[] contactsField;
        
        private string fullNameField;
        
        private gender genderField;
        
        private bool genderFieldSpecified;
        
        private identityDTO identityField;
        
        private maritalStatus maritalStatusField;
        
        private bool maritalStatusFieldSpecified;
        
        private string nationalityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contactDTO[] contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public gender gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public identityDTO identity {
            get {
                return this.identityField;
            }
            set {
                this.identityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public maritalStatus maritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maritalStatusSpecified {
            get {
                return this.maritalStatusFieldSpecified;
            }
            set {
                this.maritalStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public enum gender {
        
        /// <remarks/>
        MALE,
        
        /// <remarks/>
        FEMALE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public enum maritalStatus {
        
        /// <remarks/>
        MARRIED,
        
        /// <remarks/>
        SINGLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdirectsales.cardif.com.br/")]
    public partial class partner : identification {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void retrieveCustomerSalesCompletedEventHandler(object sender, retrieveCustomerSalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveCustomerSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveCustomerSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public retrieveCustomerSalesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((retrieveCustomerSalesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void retrievePerformanceCompletedEventHandler(object sender, retrievePerformanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrievePerformanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrievePerformanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public retrievePerformanceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((retrievePerformanceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void retrieveCommissionsCompletedEventHandler(object sender, retrieveCommissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveCommissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveCommissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public retrieveCommissionsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((retrieveCommissionsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void doSaleCompletedEventHandler(object sender, doSaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doSaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doSaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public doSaleResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((doSaleResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void updatePaymentMethodCompletedEventHandler(object sender, updatePaymentMethodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updatePaymentMethodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updatePaymentMethodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public updatePaymentMethodResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((updatePaymentMethodResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591