
CREATE TABLE PERSON(
	PERSON_ID INTEGER IDENTITY PRIMARY KEY,
	PARTNER_ID int NULL,
	USER_ID int NULL,
	PERSON_NME varchar(80) NULL,
	PERSON_SUP int NULL,
	PERSON_CPF varchar(20) NULL,
	PERSON_RG varchar(20) NULL,
	PERSON_GDR varchar(1) NULL,
	PERSON_DT_BTH datetime NULL,
	PERSON_MRT varchar(20) NULL,
	PERSON_DDD varchar(3) NULL,
	PERSON_PHO varchar(10) NULL,
	PERSON_DDD_CEL varchar(3) NULL,
	PERSON_PHO_CEL varchar(10) NULL,
	PERSON_EML varchar(80) NULL,
	PERSON_DRT int NULL,
	PERSON_ID_ML int NULL,
	PERSON_ROL varchar(50) NULL,
	PERSON_DDD_COM varchar(3) NULL,
	PERSON_PHO_COM varchar(10) NULL,
	PERSON_TYPE int NULL,
	PERSON_FULL_NME_MOTHER varchar(80) NULL,
	PERSON_RG_ORG_EMS varchar(10) NULL,
	PERSON_PIS varchar(20) NULL,
	PERSON_CNS varchar(20) NULL
)
;
