CREATE TABLE SALESMAN (
    SALESMAN_ID INTEGER IDENTITY PRIMARY KEY,
    BROKER_ID int NULL,
    PERSON_ID int NULL,
    SALESMAN_COD varchar(20) NULL,
    SALESMAN_BCH varchar(10) NULL,
    SALESMAN_ATU_BCH varchar(10) NULL,
    BCH_ID int NULL
)
;